### ISSUE TITLE
Error with SMW 4.x on Special:BrowseData

### ISSUE THREAD

**Issue by krabina** [gesinn-it-pub/mediawiki-extensions-SemanticDrilldown#9]
I used this installation in an SM 3.x installation. After upgrading of SMW to 4.0.2 I get the following error when accessing Special:BrowseData:

```
A database query error has occurred. This may indicate a bug in the software.

[YwT06-tsVI0PO43dUzcKOwAAAAk] /Special:BrowseData Wikimedia\Rdbms\DBQueryError from line 1700 of /includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?

Error 1146: Table 'kdz_cafwiki.smw_ids' doesn't exist (localhost)
Function: SDBrowseDataPage::reallyDoQuery
Query: SELECT DISTINCT ids.smw_title AS title,
ids.smw_title AS value,
ids.smw_title AS t,
ids.smw_namespace AS namespace,
ids.smw_namespace AS ns,
ids.smw_id AS id,
ids.smw_iw AS iw,
ids.smw_sortkey AS sortkey
FROM `smw_ids` ids
JOIN `smw_inst2` insts
ON ids.smw_id = insts.s_id
AND ids.smw_namespace != 14 WHERE insts.o_id IN
(SELECT smw_id FROM `smw_ids` cat_ids
WHERE smw_namespace = 14 AND (smw_title = 'Definitions' OR smw_title = '14')) ORDER BY sortkey LIMIT 251

Backtrace:

#0 /includes/libs/rdbms/database/Database.php(1684): Wikimedia\Rdbms\Database->getQueryException(string, integer, string, string)
#1 /includes/libs/rdbms/database/Database.php(1659): Wikimedia\Rdbms\Database->getQueryExceptionAndLog(string, integer, string, string)
#2 /includes/libs/rdbms/database/Database.php(1228): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#3 /includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->query(string, string, integer)
#4 /includes/libs/rdbms/database/DBConnRef.php(286): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#5 /includes/specialpage/QueryPage.php(483): Wikimedia\Rdbms\DBConnRef->query(string, string)
#6 /includes/specialpage/QueryPage.php(655): QueryPage->reallyDoQuery(integer, integer)
#7 /extensions/SemanticDrilldown/includes/specials/SDBrowseData.php(143): QueryPage->execute(NULL)
#8 /includes/specialpage/SpecialPage.php(600): SDBrowseData->execute(NULL)
#9 /includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run(NULL)
#10 /includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath(Title, RequestContext)
#11 /includes/MediaWiki.php(947): MediaWiki->performRequest()
#12 /includes/MediaWiki.php(547): MediaWiki->main()
#13 /index.php(53): MediaWiki->run()
#14 /index.php(46): wfIndexMain()
#15 {main}

```

**Comment by gesinn-it-gea** [comment]
CI tests with SMW 4.0.2 are passing without error. Did you run update.php? Which Database are you using?

**Comment by krabina** [comment]
<html><body>


Product | Version
-- | --
MediaWiki | 1.35.7
PHP | 7.4.30 (fpm-fcgi)
MariaDB | 10.3.36-MariaDB
ICU | 69.1
Semantic MediaWiki | 4.0.2 (0d6b0cb) 10:08, 21 July 2022
Semantic Drilldown | 2.1 (4ee92aa) 21:29, 7 June 2021

yes, I did run update.php without errors

**Comment by gesinn-it-gea** [comment]
SD 2.1? Please use the latest release from this repo which is 3.1.1

**Comment by krabina** [comment]
oops. Strange. I thought that was what I did. Sorry.
